/* GENERATED by tools/build_upload_index.py — do not edit by hand. */

const UPLOAD_INDEX_BUILT = "1 Aug 2026 · 16:56";
const UPLOAD_INDEX = [
  {
    "rfp": "RFP-01",
    "artifacts": {
      "0": {
        "name": "[RFP-01][Sajidul Huq][The Scope Creepers]  Solution - v1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-01%5D%5BSajidul%20Huq%5D%5BThe%20Scope%20Creepers%5D%20%20Solution%20-%20v1.0.0.xlsx",
        "time": "16:27"
      },
      "1": {
        "name": "[RFP 01][Mizuho SalaryDirect] Requirement Package - v1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP%2001%5D%5BMizuho%20SalaryDirect%5D%20Requirement%20Package%20-%20v1.0.0.xlsx",
        "time": "15:58"
      },
      "2": {
        "name": "[RFP 01][Mizuho SalaryDirect] Open Questions Register - v1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP%2001%5D%5BMizuho%20SalaryDirect%5D%20Open%20Questions%20Register%20-%20v1.0.0.xlsx",
        "time": "15:57"
      },
      "3": {
        "name": "[RFP-01][Mizuho SalaryDirect] RML Status - v1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-01%5D%5BMizuho%20SalaryDirect%5D%20RML%20Status%20-%20v1.0.0.xlsx",
        "time": "16:15"
      },
      "4": {
        "name": "[RFP-01][Mizuho SalaryDirect] UCM Classification - v1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-01%5D%5BMizuho%20SalaryDirect%5D%20UCM%20Classification%20-%20v1.0.0.xlsx",
        "time": "15:57"
      },
      "5": {
        "name": "[RFP 01][Mizuho SalaryDirect] Reverse Validation Workshop - v1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP%2001%5D%5BMizuho%20SalaryDirect%5D%20Reverse%20Validation%20Workshop%20-%20v1.0.0.xlsx",
        "time": "15:58"
      },
      "6": {
        "name": "[RFP-01][Mizuho SalaryDirect] Solution_Approval_and_Tech_Risk - v1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-01%5D%5BMizuho%20SalaryDirect%5D%20Solution_Approval_and_Tech_Risk%20-%20v1.0.0.xlsx",
        "time": "16:02"
      },
      "8": {
        "name": "[RFP 01][Mizuho SalaryDirect] Deliverable WBS - v1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP%2001%5D%5BMizuho%20SalaryDirect%5D%20Deliverable%20WBS%20-%20v1.0.0.xlsx",
        "time": "16:00"
      },
      "9": {
        "name": "[RFP-01][Mizuho SalaryDirect] Risk Buffer + Assumptions - v1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-01%5D%5BMizuho%20SalaryDirect%5D%20Risk%20Buffer%20%2B%20Assumptions%20-%20v1.0.0.xlsx",
        "time": "16:24"
      },
      "10": {
        "name": "[RFP-01][Mizuho SalaryDirect] Scope and Margin Baseline - v1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-01%5D%5BMizuho%20SalaryDirect%5D%20Scope%20and%20Margin%20Baseline%20-%20v1.0.0.xlsx",
        "time": "16:02"
      },
      "11": {
        "name": "[RFP 01][Mizuho SalaryDirect] BRC Decision - v1.0.10.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP%2001%5D%5BMizuho%20SalaryDirect%5D%20BRC%20Decision%20-%20v1.0.10.xlsx",
        "time": "16:00"
      },
      "12": {
        "name": "[RFP-01] [Mizuho SalaryDirect] Technical Proposal - v1.0.0.pptx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-01%5D%20%5BMizuho%20SalaryDirect%5D%20Technical%20Proposal%20-%20v1.0.0.pptx",
        "time": "16:00"
      }
    }
  },
  {
    "rfp": "RFP-02",
    "artifacts": {
      "0": {
        "name": "[RFP-02][Shahjalal Hossain][404 - Free Work Not Found] BidHub Auction Marketplace - v1.0.0.docx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-02%5D%5BShahjalal%20Hossain%5D%5B404%20-%20Free%20Work%20Not%20Found%5D%20BidHub%20Auction%20Marketplace%20-%20v1.0.0.docx",
        "time": "12:33"
      },
      "1": {
        "name": "[RFP-02][BidHub Auction Marketplace] Requirement Package - v1.0.0.zip",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-02%5D%5BBidHub%20Auction%20Marketplace%5D%20Requirement%20Package%20-%20v1.0.0.zip",
        "time": "15:06"
      },
      "2": {
        "name": "[RFP-02][BidHub Auction Marketplace] Open Questions Register -v1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-02%5D%5BBidHub%20Auction%20Marketplace%5D%20Open%20Questions%20Register%20-v1.0.0.xlsx",
        "time": "15:24"
      },
      "4": {
        "name": "[RFP-02][BidHub Auction Marketplace] UCM Classification -v1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-02%5D%5BBidHub%20Auction%20Marketplace%5D%20UCM%20Classification%20-v1.0.0.xlsx",
        "time": "15:16"
      },
      "5": {
        "name": "[RFP-02][BidHub Auction Marketplace] RVW Record -v1.0.0.zip",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-02%5D%5BBidHub%20Auction%20Marketplace%5D%20RVW%20Record%20-v1.0.0.zip",
        "time": "15:28"
      },
      "6": {
        "name": "[RFP-02][BidHub Auction Marketplace] Risk-Assumption Register -v1.0.0.zip",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-02%5D%5BBidHub%20Auction%20Marketplace%5D%20Risk-Assumption%20Register%20-v1.0.0.zip",
        "time": "15:30"
      },
      "7": {
        "name": "[RFP-02][BidHub Auction Marketplace] Solution Approval -v1.0.0.pdf",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-02%5D%5BBidHub%20Auction%20Marketplace%5D%20Solution%20Approval%20-v1.0.0.pdf",
        "time": "15:54"
      },
      "8": {
        "name": "[RFP-02][BidHub Auction Marketplace] Deliverable WBS -v1.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-02%5D%5BBidHub%20Auction%20Marketplace%5D%20Deliverable%20WBS%20-v1.0.xlsx",
        "time": "16:31"
      },
      "12": {
        "name": "[RFP-02][BidHub Auction Marketplace] Technical Proposal -v1.0.0.pdf",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-02%5D%5BBidHub%20Auction%20Marketplace%5D%20Technical%20Proposal%20-v1.0.0.pdf",
        "time": "16:01"
      }
    }
  },
  {
    "rfp": "RFP-03",
    "artifacts": {
      "0": {
        "name": "[RFP-03][Abdul Halim][Ctrl+Alt+Deliver] Midori-Home - v1.0.0.docx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-03%5D%5BAbdul%20Halim%5D%5BCtrl%2BAlt%2BDeliver%5D%20Midori-Home%20-%20v1.0.0.docx",
        "time": "12:33"
      },
      "4": {
        "name": "[RFP 03][Midori Home]UCM_Classification-v1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP%2003%5D%5BMidori%20Home%5DUCM_Classification-v1.0.0.xlsx",
        "time": "15:56"
      },
      "5": {
        "name": "[RFP 03][Midori Home]RVW Record-v1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP%2003%5D%5BMidori%20Home%5DRVW%20Record-v1.0.0.xlsx",
        "time": "15:56"
      },
      "6": {
        "name": "[RFP 03][Midori Home]Solution-Tech_Risk-v1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP%2003%5D%5BMidori%20Home%5DSolution-Tech_Risk-v1.0.0.xlsx",
        "time": "15:57"
      },
      "8": {
        "name": "[RFP 03][Midori Home]Deliverable WBS-v1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP%2003%5D%5BMidori%20Home%5DDeliverable%20WBS-v1.0.0.xlsx",
        "time": "15:59"
      },
      "9": {
        "name": "[RFP 03][Midori Home]Risk_Buffer-PRS-v1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP%2003%5D%5BMidori%20Home%5DRisk_Buffer-PRS-v1.0.0.xlsx",
        "time": "16:04"
      },
      "10": {
        "name": "[RFP 03][Midori Home]Scope-Margin_Baseline-v1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP%2003%5D%5BMidori%20Home%5DScope-Margin_Baseline-v1.0.0.xlsx",
        "time": "15:59"
      },
      "11": {
        "name": "[RFP 03][Midori Home]BRC_Decision-v1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP%2003%5D%5BMidori%20Home%5DBRC_Decision-v1.0.0.xlsx",
        "time": "16:00"
      },
      "12": {
        "name": "[RFP 03][Midori Home]Ctrl+Alt+Deliver_Proposal-v1.0.0.pptx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP%2003%5D%5BMidori%20Home%5DCtrl%2BAlt%2BDeliver_Proposal-v1.0.0.pptx",
        "time": "16:11"
      }
    }
  },
  {
    "rfp": "RFP-04",
    "artifacts": {
      "0": {
        "name": "[RFP-04][Dewan Shamsul Alam][Swipe Right to Sign Off] NovaCart Mobile - v1.0.0.docx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-04%5D%5BDewan%20Shamsul%20Alam%5D%5BSwipe%20Right%20to%20Sign%20Off%5D%20NovaCart%20Mobile%20-%20v1.0.0.docx",
        "time": "12:33"
      },
      "4": {
        "name": "[RFP 04][NovaCart Mobile] 04_UCM_Classification V-1.0.0.pdf",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP%2004%5D%5BNovaCart%20Mobile%5D%2004_UCM_Classification%20V-1.0.0.pdf",
        "time": "15:09"
      },
      "6": {
        "name": "[RFP 04][NovaCart Mobile] 07_Solution_Approval_Technology_Risk_Assessment V-1.0.0.pdf",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP%2004%5D%5BNovaCart%20Mobile%5D%2007_Solution_Approval_Technology_Risk_Assessment%20V-1.0.0.pdf",
        "time": "15:38"
      },
      "8": {
        "name": "[RFP 04][NovaCart Mobile] 08_WBS_Estimation V-1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP%2004%5D%5BNovaCart%20Mobile%5D%2008_WBS_Estimation%20V-1.0.0.xlsx",
        "time": "16:34"
      },
      "9": {
        "name": "[RFP 04][NovaCart Mobile] 09_Risk_Buffer_Estimation_Assumptions_Log V-1.0.0.pdf",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP%2004%5D%5BNovaCart%20Mobile%5D%2009_Risk_Buffer_Estimation_Assumptions_Log%20V-1.0.0.pdf",
        "time": "15:46"
      },
      "10": {
        "name": "[RFP 04][NovaCart Mobile] 11_Scope_Baseline_Margin_Baseline V-1.0.0.pdf",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP%2004%5D%5BNovaCart%20Mobile%5D%2011_Scope_Baseline_Margin_Baseline%20V-1.0.0.pdf",
        "time": "16:06"
      },
      "11": {
        "name": "[RFP 04][NovaCart Mobile] 10_BRC_Decision_Record V-1.0.0.pdf",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP%2004%5D%5BNovaCart%20Mobile%5D%2010_BRC_Decision_Record%20V-1.0.0.pdf",
        "time": "16:31"
      },
      "12": {
        "name": "[RFP 04][NovaCart Mobile] 12_NovaCart_Mobile_Proposal V1.0.0.pdf",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP%2004%5D%5BNovaCart%20Mobile%5D%2012_NovaCart_Mobile_Proposal%20V1.0.0.pdf",
        "time": "16:30"
      }
    }
  },
  {
    "rfp": "RFP-05",
    "artifacts": {
      "0": {
        "name": "[RFP-05][Mostafizur Rahman][Push Notification Nation] Astra Mobile Pack - V1.0.0.docx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-05%5D%5BMostafizur%20Rahman%5D%5BPush%20Notification%20Nation%5D%20Astra%20Mobile%20Pack%20-%20V1.0.0.docx",
        "time": "15:00"
      },
      "1": {
        "name": "[RFP 05][Astra Mobile App] Requirement Package V-1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP%2005%5D%5BAstra%20Mobile%20App%5D%20Requirement%20Package%20V-1.0.0.xlsx",
        "time": "15:22"
      },
      "2": {
        "name": "[RFP 05][Astra Mobile App] Open Questions Register V-1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP%2005%5D%5BAstra%20Mobile%20App%5D%20Open%20Questions%20Register%20V-1.0.0.xlsx",
        "time": "15:22"
      },
      "3": {
        "name": "[RFP 05][Astra Mobile App] RML Status V-1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP%2005%5D%5BAstra%20Mobile%20App%5D%20RML%20Status%20V-1.0.0.xlsx",
        "time": "15:22"
      },
      "4": {
        "name": "[RFP 05][Astra Mobile App] UCM Classification V-1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP%2005%5D%5BAstra%20Mobile%20App%5D%20UCM%20Classification%20V-1.0.0.xlsx",
        "time": "15:22"
      },
      "5": {
        "name": "[RFP 05][Astra Mobile App] RVW Record V-1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP%2005%5D%5BAstra%20Mobile%20App%5D%20RVW%20Record%20V-1.0.0.xlsx",
        "time": "15:22"
      },
      "6": {
        "name": "[RFP 05][Astra Mobile App] Risk-Assumption Register V-1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP%2005%5D%5BAstra%20Mobile%20App%5D%20Risk-Assumption%20Register%20V-1.0.0.xlsx",
        "time": "15:22"
      },
      "7": {
        "name": "[RFP 05][Astra Mobile App] Solution Approval V-1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP%2005%5D%5BAstra%20Mobile%20App%5D%20Solution%20Approval%20V-1.0.0.xlsx",
        "time": "15:22"
      },
      "8": {
        "name": "[RFP 05][Astra Mobile App] Deliverable WBS V-1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP%2005%5D%5BAstra%20Mobile%20App%5D%20Deliverable%20WBS%20V-1.0.0.xlsx",
        "time": "16:09"
      },
      "10": {
        "name": "[RFP 05][Astra Mobile App] Scope + Margin Baseline V-1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP%2005%5D%5BAstra%20Mobile%20App%5D%20Scope%20%2B%20Margin%20Baseline%20V-1.0.0.xlsx",
        "time": "15:22"
      },
      "11": {
        "name": "[RFP 05][Astra Mobile App] BRC Decision V-1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP%2005%5D%5BAstra%20Mobile%20App%5D%C2%A0BRC%20Decision%C2%A0V-1.0.0.xlsx",
        "time": "15:49"
      },
      "12": {
        "name": "[RFP 05][Astra Mobile App] Technical Proposal V-1.0.0.pptx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP%2005%5D%5BAstra%20Mobile%20App%5D%20Technical%20Proposal%20V-1.0.0.pptx",
        "time": "16:11"
      }
    }
  },
  {
    "rfp": "RFP-06",
    "artifacts": {
      "0": {
        "name": "[RFP-06][Mamun Ahmed Khan][The App-solute Owners] SolaraLife - v1.0.0.docx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-06%5D%5BMamun%20Ahmed%20Khan%5D%5BThe%20App-solute%20Owners%5D%20SolaraLife%20-%20v1.0.0.docx",
        "time": "12:33"
      },
      "1": {
        "name": "[RFP-06][SolaraLife] Requirement Package - v1.0.0.md",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-06%5D%5BSolaraLife%5D%20Requirement%20Package%20-%20v1.0.0.md",
        "time": "16:32"
      },
      "2": {
        "name": "[RFP-06][SolaraLife] Open Questions Register - v1.0.1.md",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-06%5D%5BSolaraLife%5D%20Open%20Questions%20Register%20-%20v1.0.1.md",
        "time": "16:32"
      },
      "3": {
        "name": "[RFP-06][SolaraLife] RML Status - v1.0.2.md",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-06%5D%5BSolaraLife%5D%20RML%20Status%20-%20v1.0.2.md",
        "time": "16:32"
      },
      "4": {
        "name": "[RFP-06][SolaraLife] UCM Classification - v1.0.2.md",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-06%5D%5BSolaraLife%5D%20UCM%20Classification%20-%20v1.0.2.md",
        "time": "16:32"
      },
      "5": {
        "name": "[RFP-06][SolaraLife] RVW Record - v1.0.0.md",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-06%5D%5BSolaraLife%5D%20RVW%20Record%20-%20v1.0.0.md",
        "time": "16:32"
      },
      "6": {
        "name": "[RFP-06][SolaraLife] Risk-Assumption Register - v1.0.1.md",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-06%5D%5BSolaraLife%5D%20Risk-Assumption%20Register%20-%20v1.0.1.md",
        "time": "16:32"
      },
      "7": {
        "name": "[RFP-06][SolaraLife] Solution Approval - v1.0.0.docx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-06%5D%5BSolaraLife%5D%20Solution%20Approval%20-%20v1.0.0.docx",
        "time": "16:32"
      },
      "8": {
        "name": "[RFP-06][SolaraLife] Deliverable WBS - v1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-06%5D%5BSolaraLife%5D%20Deliverable%20WBS%20-%20v1.0.0.xlsx",
        "time": "16:32"
      },
      "9": {
        "name": "[RFP-06][SolaraLife] Risk Buffer + Assumptions - v1.0.0.md",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-06%5D%5BSolaraLife%5D%20Risk%20Buffer%20%2B%20Assumptions%20-%20v1.0.0.md",
        "time": "16:32"
      },
      "10": {
        "name": "[RFP-06][SolaraLife] Scope + Margin Baseline - v1.0.0.md",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-06%5D%5BSolaraLife%5D%20Scope%20%2B%20Margin%20Baseline%20-%20v1.0.0.md",
        "time": "16:54"
      },
      "12": {
        "name": "[RFP-06][SolaraLife] Technical Proposal - v1.0.0.pptx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-06%5D%5BSolaraLife%5D%20Technical%20Proposal%20-%20v1.0.0.pptx",
        "time": "16:33"
      }
    }
  },
  {
    "rfp": "RFP-07",
    "artifacts": {
      "0": {
        "name": "[RFP-07][Dipankar Das Shovon][Bare Metal Bidders] Kitagawa Battery - v1.0.0.docx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-07%5D%5BDipankar%20Das%20Shovon%5D%5BBare%20Metal%20Bidders%5D%20Kitagawa%20Battery%20-%20v1.0.0.docx",
        "time": "12:33"
      },
      "9": {
        "name": "[RfP-07] PackTrace_Estimation_v1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRfP-07%5D%20PackTrace_Estimation_v1.0.0.xlsx",
        "time": "16:46"
      }
    }
  },
  {
    "rfp": "RFP-08",
    "artifacts": {
      "0": {
        "name": "[RFP-08][Iftekhar Uddin Ahmed][The Ctrl Freaks] Hoshino Sight 8 - v1.0.0.docx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-08%5D%5BIftekhar%20Uddin%20Ahmed%5D%5BThe%20Ctrl%20Freaks%5D%20Hoshino%20Sight%208%20-%20v1.0.0.docx",
        "time": "12:33"
      },
      "2": {
        "name": "[RFP 08][The Ctrl Freaks] Open Questions Register V-1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP%2008%5D%5BThe%20Ctrl%20Freaks%5D%20Open%20Questions%20Register%20V-1.0.0.xlsx",
        "time": "16:33"
      },
      "4": {
        "name": "[RFP 08]UCM Classification (Stable  Partially Defined  High Uncertainty  R&D) V-1.0.0 - Copy.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP%2008%5DUCM%20Classification%20%28Stable%20%20Partially%20Defined%20%20High%20Uncertainty%20%20R%26D%29%20V-1.0.0%20-%20Copy.xlsx",
        "time": "16:33"
      },
      "5": {
        "name": "[RFP 08] Reverse Validation Workshop Record V-1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP%2008%5D%20Reverse%20Validation%20Workshop%20Record%20V-1.0.0.xlsx",
        "time": "16:33"
      },
      "6": {
        "name": "[RFP 08] Assumption Register (Client-visible) V-1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP%2008%5D%20Assumption%20Register%20%28Client-visible%29%20V-1.0.0.xlsx",
        "time": "16:33"
      },
      "7": {
        "name": "[RFP 08] Solution Approval Note (+ Technology Risk Assessment) V-1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP%2008%5D%20Solution%20Approval%20Note%20%28%2B%20Technology%20Risk%20Assessment%29%20V-1.0.0.xlsx",
        "time": "16:33"
      },
      "8": {
        "name": "[RFP 08] WBS V-1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP%2008%5D%20WBS%20V-1.0.0.xlsx",
        "time": "16:33"
      },
      "9": {
        "name": "[RFP 08][The Ctrl Freaks] Estimation V-1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP%2008%5D%5BThe%20Ctrl%20Freaks%5D%20Estimation%20V-1.0.0.xlsx",
        "time": "16:38"
      },
      "10": {
        "name": "[RFP08][The Ctrl Freaks] Margin_Analysis.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP08%5D%5BThe%20Ctrl%20Freaks%5D%20Margin_Analysis.xlsx",
        "time": "16:52"
      },
      "12": {
        "name": "[RFP-08][The Ctrl Freaks] Technical Proposal.docx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-08%5D%5BThe%20Ctrl%20Freaks%5D%20Technical%20Proposal.docx",
        "time": "16:29"
      }
    }
  },
  {
    "rfp": "RFP-09",
    "artifacts": {
      "0": {
        "name": "[RFP-09][Shaiful Islam][React & Sign-Off] FlyerBank Direct AMS - v1.0.0.docx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-09%5D%5BShaiful%20Islam%5D%5BReact%20%26%20Sign-Off%5D%20FlyerBank%20Direct%20AMS%20-%20v1.0.0.docx",
        "time": "12:33"
      },
      "1": {
        "name": "[RFP-09][Flyer Direct] Requirement Package - v2.1.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-09%5D%5BFlyer%20Direct%5D%20Requirement%20Package%20-%20v2.1.0.xlsx",
        "time": "15:47"
      },
      "2": {
        "name": "[RFP-09][Flyer Direct] Open Questions Register - v1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-09%5D%5BFlyer%20Direct%5D%20Open%20Questions%20Register%20-%20v1.0.0.xlsx",
        "time": "15:47"
      },
      "4": {
        "name": "[RFP-09][Flyer Direct] UCM Classification - v1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-09%5D%5BFlyer%20Direct%5D%20UCM%20Classification%20-%20v1.0.0.xlsx",
        "time": "15:47"
      },
      "5": {
        "name": "[RFP-09][Flyer Direct] RVW Record - v1.0.1.pptx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-09%5D%5BFlyer%20Direct%5D%20RVW%20Record%20-%20v1.0.1.pptx",
        "time": "15:47"
      },
      "6": {
        "name": "[RFP-09][Flyer Direct] Risk-Assumption Register - v1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-09%5D%5BFlyer%20Direct%5D%20Risk-Assumption%20Register%20-%20v1.0.0.xlsx",
        "time": "15:47"
      },
      "7": {
        "name": "[RFP-09][Flyer Direct] Solution Approval - v1.0.0.docx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-09%5D%5BFlyer%20Direct%5D%20Solution%20Approval%20-%20v1.0.0.docx",
        "time": "15:47"
      },
      "8": {
        "name": "[RFP-09][Flyer Direct] Deliverable WBS - v2.1.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-09%5D%5BFlyer%20Direct%5D%20Deliverable%20WBS%20-%20v2.1.0.xlsx",
        "time": "16:02"
      },
      "9": {
        "name": "[RFP-09][Flyer Direct] Risk Buffer + Assumptions - v1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-09%5D%5BFlyer%20Direct%5D%20Risk%20Buffer%20%2B%20Assumptions%20-%20v1.0.0.xlsx",
        "time": "16:04"
      },
      "10": {
        "name": "[RFP-09][Flyer Direct] Scope + Margin Baseline - v1.6.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-09%5D%5BFlyer%20Direct%5D%20Scope%20%2B%20Margin%20Baseline%20-%20v1.6.0.xlsx",
        "time": "16:55"
      },
      "11": {
        "name": "[RFP-09][Flyer Direct] BRC Decision - v1.1.0.docx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-09%5D%5BFlyer%20Direct%5D%20BRC%20Decision%20-%20v1.1.0.docx",
        "time": "16:05"
      },
      "12": {
        "name": "[RFP-09][Flyer Direct] Technical Proposal - v1.1.2.pptx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-09%5D%5BFlyer%20Direct%5D%20Technical%20Proposal%20-%20v1.1.2.pptx",
        "time": "16:07"
      }
    }
  },
  {
    "rfp": "RFP-10",
    "artifacts": {
      "0": {
        "name": "[RFP-10][Partha Pratim Sarkar][The Baseline Defenders] Wakaba - v1.0.0.docx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-10%5D%5BPartha%20Pratim%20Sarkar%5D%5BThe%20Baseline%20Defenders%5D%20Wakaba%20-%20v1.0.0.docx",
        "time": "12:33"
      },
      "2": {
        "name": "[RFP-10] Open Question Register.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-10%5D%20Open%20Question%20Register.xlsx",
        "time": "16:22"
      },
      "3": {
        "name": "[RFP-10] RML_Classification.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-10%5D%20RML_Classification.xlsx",
        "time": "16:22"
      },
      "4": {
        "name": "[RFP-10] UCM_Classification.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-10%5D%20UCM_Classification.xlsx",
        "time": "16:22"
      },
      "6": {
        "name": "[RFP-10] Solution_and_Risk_v1.3.0_detailed_updated.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-10%5D%20Solution_and_Risk_v1.3.0_detailed_updated.xlsx",
        "time": "16:22"
      },
      "8": {
        "name": "[RFP-10] Deliverable WBS.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-10%5D%20Deliverable%20WBS.xlsx",
        "time": "16:22"
      },
      "9": {
        "name": "[RFP-10]Buffer_and_Assumptions_v1.3.0_detailed_updated.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-10%5DBuffer_and_Assumptions_v1.3.0_detailed_updated.xlsx",
        "time": "16:22"
      },
      "10": {
        "name": "[RFP-10] Margin_Analysis.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-10%5D%20Margin_Analysis.xlsx",
        "time": "16:22"
      },
      "11": {
        "name": "[RFP-10] BRC_Go-NoGo_Decision_Record_RFP-10_Wakaba.docx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-10%5D%20BRC_Go-NoGo_Decision_Record_RFP-10_Wakaba.docx",
        "time": "16:22"
      },
      "12": {
        "name": "[RFP-10] Wakaba Maintenance Labo Proposal 1.0.1.pptx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-10%5D%20Wakaba%20Maintenance%20Labo%20Proposal%201.0.1.pptx",
        "time": "16:22"
      }
    }
  },
  {
    "rfp": "RFP-11",
    "artifacts": {
      "0": {
        "name": "[RFP-11][ABM Mahbubur Rahman][Sixty-Seven Shades of Ownership] Legacy-Migration Suzuran SPL StockOne - v1.0.0.docx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-11%5D%5BABM%20Mahbubur%20Rahman%5D%5BSixty-Seven%20Shades%20of%20Ownership%5D%20Legacy-Migration%20Suzuran%20SPL%20StockOne%20-%20v1.0.0.docx",
        "time": "12:33"
      },
      "1": {
        "name": "[RFP-11][SPL StockOne] Requirement Package - v1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-11%5D%5BSPL%20StockOne%5D%20Requirement%20Package%20-%20v1.0.0.xlsx",
        "time": "15:43"
      },
      "2": {
        "name": "[RFP-11][SPL StockOne] Open Questions Register - v1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-11%5D%5BSPL%20StockOne%5D%20Open%20Questions%20Register%20-%20v1.0.0.xlsx",
        "time": "15:43"
      },
      "3": {
        "name": "[RFP-11][SPL StockOne] RML Status Register - v1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-11%5D%5BSPL%20StockOne%5D%20RML%20Status%20Register%20-%20v1.0.0.xlsx",
        "time": "15:43"
      },
      "4": {
        "name": "[RFP-11][SPL StockOne] UCM Classification - v1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-11%5D%5BSPL%20StockOne%5D%20UCM%20Classification%20-%20v1.0.0.xlsx",
        "time": "15:43"
      },
      "5": {
        "name": "[RFP-11][SPL StockOne] Reverse Validation Workshop Record - v1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-11%5D%5BSPL%20StockOne%5D%20Reverse%20Validation%20Workshop%20Record%20-%20v1.0.0.xlsx",
        "time": "15:43"
      },
      "6": {
        "name": "[RFP-11][SPL StockOne] Risk Assumption Register - v1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-11%5D%5BSPL%20StockOne%5D%20Risk%20Assumption%20Register%20-%20v1.0.0.xlsx",
        "time": "15:43"
      },
      "7": {
        "name": "[RFP-11][SPL StockOne] Solution Approval Note TRA - v1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-11%5D%5BSPL%20StockOne%5D%20Solution%20Approval%20Note%20TRA%20-%20v1.0.0.xlsx",
        "time": "15:43"
      },
      "8": {
        "name": "[RFP-11][SPL StockOne] Deliverable Based WBS - v1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-11%5D%5BSPL%20StockOne%5D%20Deliverable%20Based%20WBS%20-%20v1.0.0.xlsx",
        "time": "16:01"
      },
      "9": {
        "name": "[RFP-11][SPL StockOne] Risk Buffer Estimation Assumptions - v1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-11%5D%5BSPL%20StockOne%5D%20Risk%20Buffer%20Estimation%20Assumptions%20-%20v1.0.0.xlsx",
        "time": "16:04"
      },
      "10": {
        "name": "[RFP-11][SPL StockOne] Scope and Margin Baseline - v1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-11%5D%5BSPL%20StockOne%5D%20Scope%20and%20Margin%20Baseline%20-%20v1.0.0.xlsx",
        "time": "16:35"
      },
      "11": {
        "name": "[RFP-11][SPL StockOne] BRC Decision Record - v1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-11%5D%5BSPL%20StockOne%5D%20BRC%20Decision%20Record%20-%20v1.0.0.xlsx",
        "time": "16:37"
      }
    }
  },
  {
    "rfp": "RFP-12",
    "artifacts": {
      "0": {
        "name": "[RFP-12][Himadri Mondol][Not My Bug Anymore] Nexus-Telecom QA-PartneR - v1.0.0.docx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-12%5D%5BHimadri%20Mondol%5D%5BNot%20My%20Bug%20Anymore%5D%20Nexus-Telecom%20QA-PartneR%20-%20v1.0.0.docx",
        "time": "12:33"
      },
      "1": {
        "name": "[RFP 12][Not My Bug Anymore] Requirement Package V-0.0.1.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP%2012%5D%5BNot%20My%20Bug%20Anymore%5D%20Requirement%20Package%20V-0.0.1.xlsx",
        "time": "16:07"
      },
      "2": {
        "name": "[RFP 12][Not My Bug Anymore] Open Questions Register V-0.0.1.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP%2012%5D%5BNot%20My%20Bug%20Anymore%5D%20Open%20Questions%20Register%20V-0.0.1.xlsx",
        "time": "15:41"
      },
      "3": {
        "name": "[RFP 12][Not My Bug Anymore] RML Status UCM Classification V-0.0.1.pdf",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP%2012%5D%5BNot%20My%20Bug%20Anymore%5D%20RML%20Status%20UCM%20Classification%20V-0.0.1.pdf",
        "time": "15:40"
      },
      "5": {
        "name": "[RFP 12][Not My Bug Anymore]  RVW Record V-0.0.1.pdf",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP%2012%5D%5BNot%20My%20Bug%20Anymore%5D%20%20RVW%20Record%20V-0.0.1.pdf",
        "time": "16:31"
      },
      "6": {
        "name": "[RFP 12][Not My Bug Anymore] Risk  Assumption Register (client-visible) V-0.0.1.docx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP%2012%5D%5BNot%20My%20Bug%20Anymore%5D%20Risk%20%20Assumption%20Register%20%28client-visible%29%20V-0.0.1.docx",
        "time": "15:33"
      },
      "7": {
        "name": "[RFP 12][Not My Bug Anymore] Solution Approval V-0.0.1.docx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP%2012%5D%5BNot%20My%20Bug%20Anymore%5D%20Solution%20Approval%20V-0.0.1.docx",
        "time": "16:14"
      },
      "8": {
        "name": "[RFP 12][Not My Bug Anymore] Deliverable-based WBS (100% traceable) V-0.0.1.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP%2012%5D%5BNot%20My%20Bug%20Anymore%5D%20Deliverable-based%20WBS%20%28100%25%20traceable%29%20V-0.0.1.xlsx",
        "time": "15:33"
      },
      "9": {
        "name": "[RFP 12][Not My Bug Anymore] Estimation V-0.0.1.docx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP%2012%5D%5BNot%20My%20Bug%20Anymore%5D%20Estimation%20V-0.0.1.docx",
        "time": "16:19"
      },
      "11": {
        "name": "[RFP 12][Not My Bug Anymore] BRC Decision V-0.0.1.docx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP%2012%5D%5BNot%20My%20Bug%20Anymore%5D%20BRC%20Decision%20V-0.0.1.docx",
        "time": "16:44"
      }
    }
  },
  {
    "rfp": "RFP-13",
    "artifacts": {
      "0": {
        "name": "[RFP-13][Nadim Hossain][Test Case Closed] Migration-QA - v1.0.0.pdf",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-13%5D%5BNadim%20Hossain%5D%5BTest%20Case%20Closed%5D%20Migration-QA%20-%20v1.0.0.pdf",
        "time": "12:33"
      },
      "1": {
        "name": "[RFP 13][Test Case Closed] Requirement Package V-1.0.0.docx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP%2013%5D%5BTest%20Case%20Closed%5D%20Requirement%20Package%20V-1.0.0.docx",
        "time": "16:32"
      },
      "2": {
        "name": "[RFP 13][Test Case Closed] Open Questions Register -v1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP%2013%5D%5BTest%20Case%20Closed%5D%20Open%20Questions%20Register%20-v1.0.0.xlsx",
        "time": "16:32"
      },
      "4": {
        "name": "[RFP 13][Test Case Closed] UCM Classification V-1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP%2013%5D%5BTest%20Case%20Closed%5D%20UCM%20Classification%20V-1.0.0.xlsx",
        "time": "16:32"
      },
      "5": {
        "name": "[RFP 13][Test Case Closed] RVW Record -v1.0.0.pptx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP%2013%5D%5BTest%20Case%20Closed%5D%20RVW%20Record%20-v1.0.0.pptx",
        "time": "16:32"
      },
      "6": {
        "name": "[RFP 13][Test Case Closed] Risk  Assumption Register (client-visible) V-0.0.1.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP%2013%5D%5BTest%20Case%20Closed%5D%20Risk%20%20Assumption%20Register%20%28client-visible%29%20V-0.0.1.xlsx",
        "time": "16:32"
      },
      "7": {
        "name": "[RFP 13][Test Case Closed] Solution Approval V-1.0.0.docx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP%2013%5D%5BTest%20Case%20Closed%5D%20Solution%20Approval%20V-1.0.0.docx",
        "time": "16:32"
      },
      "8": {
        "name": "[RFP 13][Test Case Closed] Deliverable WBS V-1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP%2013%5D%5BTest%20Case%20Closed%5D%20Deliverable%20WBS%20V-1.0.0.xlsx",
        "time": "16:36"
      },
      "12": {
        "name": "[RFP-13][Test Case Closed]Technical Proposal-v1.0.0.pptx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-13%5D%5BTest%20Case%20Closed%5DTechnical%20Proposal-v1.0.0.pptx",
        "time": "16:54"
      }
    }
  },
  {
    "rfp": "RFP-14",
    "artifacts": {
      "0": {
        "name": "[RFP-14][Azizul Islam][The Tolerance Negotiators] NORDTEK OY NT-2026-KOSKI2-BD - v1.0.0.docx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-14%5D%5BAzizul%20Islam%5D%5BThe%20Tolerance%20Negotiators%5D%20NORDTEK%20OY%20NT-2026-KOSKI2-BD%20-%20v1.0.0.docx",
        "time": "12:33"
      },
      "1": {
        "name": "[RFP-14][KOSKI-2] Requirement Package - v1.1.0.pdf",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-14%5D%5BKOSKI-2%5D%20Requirement%20Package%20-%20v1.1.0.pdf",
        "time": "16:06"
      },
      "2": {
        "name": "[RFP-14][KOSKI-2] Open Questions Register - v1.1.0.pdf",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-14%5D%5BKOSKI-2%5D%20Open%20Questions%20Register%20-%20v1.1.0.pdf",
        "time": "16:06"
      },
      "3": {
        "name": "[RFP-14][KOSKI-2] RML Status - v1.1.0.pdf",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-14%5D%5BKOSKI-2%5D%20RML%20Status%20-%20v1.1.0.pdf",
        "time": "16:06"
      },
      "4": {
        "name": "[RFP-14][KOSKI-2] UCM Classification - v1.1.0.pdf",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-14%5D%5BKOSKI-2%5D%20UCM%20Classification%20-%20v1.1.0.pdf",
        "time": "16:06"
      },
      "5": {
        "name": "[RFP-14][KOSKI-2] RVW Record - v1.1.0.pdf",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-14%5D%5BKOSKI-2%5D%20RVW%20Record%20-%20v1.1.0.pdf",
        "time": "16:06"
      },
      "6": {
        "name": "[RFP-14][KOSKI-2] Risk-Assumption Register - v1.1.0.pdf",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-14%5D%5BKOSKI-2%5D%20Risk-Assumption%20Register%20-%20v1.1.0.pdf",
        "time": "16:06"
      },
      "7": {
        "name": "[RFP-14][KOSKI-2] Solution Approval - v1.1.0.pdf",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-14%5D%5BKOSKI-2%5D%20Solution%20Approval%20-%20v1.1.0.pdf",
        "time": "16:06"
      },
      "8": {
        "name": "[RFP-14][KOSKI-2] Deliverable WBS - v1.1.0.pdf",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-14%5D%5BKOSKI-2%5D%20Deliverable%20WBS%20-%20v1.1.0.pdf",
        "time": "16:06"
      },
      "9": {
        "name": "[RFP-14][KOSKI-2] Risk Buffer + Assumptions - v1.1.0.pdf",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-14%5D%5BKOSKI-2%5D%20Risk%20Buffer%20%2B%20Assumptions%20-%20v1.1.0.pdf",
        "time": "16:06"
      },
      "10": {
        "name": "[RFP-14][KOSKI-2] Scope + Margin Baseline - v1.1.0.pdf",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-14%5D%5BKOSKI-2%5D%20Scope%20%2B%20Margin%20Baseline%20-%20v1.1.0.pdf",
        "time": "16:06"
      },
      "11": {
        "name": "[RFP-14][KOSKI-2] BRC Decision - v1.1.0.pdf",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-14%5D%5BKOSKI-2%5D%20BRC%20Decision%20-%20v1.1.0.pdf",
        "time": "16:06"
      },
      "12": {
        "name": "[RFP-14][KOSKI-2] Technical Proposal - v1.1.0.pdf",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-14%5D%5BKOSKI-2%5D%20Technical%20Proposal%20-%20v1.1.0.pdf",
        "time": "16:06"
      }
    }
  },
  {
    "rfp": "RFP-15",
    "artifacts": {
      "0": {
        "name": "[RFP-15][Sayeedul Islam][Torque of the Town] Nordkaross VIKEN - v1.0.0.pdf",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-15%5D%5BSayeedul%20Islam%5D%5BTorque%20of%20the%20Town%5D%20Nordkaross%20VIKEN%20-%20v1.0.0.pdf",
        "time": "12:33"
      },
      "3": {
        "name": "[RFP 15][VIKEN-2 · New B-segment battery-electric crossover]RML_Verification_and_UCM_Analysis.pptx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP%2015%5D%5BVIKEN-2%20%C2%B7%20New%20B-segment%20battery-electric%20crossover%5DRML_Verification_and_UCM_Analysis.pptx",
        "time": "16:09"
      },
      "6": {
        "name": "[RFP 15][VIKEN-2 · New B-segment battery-electric crossover]Risk_Assumption_Register_CR.pptx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP%2015%5D%5BVIKEN-2%20%C2%B7%20New%20B-segment%20battery-electric%20crossover%5DRisk_Assumption_Register_CR.pptx",
        "time": "16:09"
      },
      "8": {
        "name": "[RFP 15][VIKEN-2 · New B-segment battery-electric crossover]Deliverable_Based_WBS 1.pptx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP%2015%5D%5BVIKEN-2%20%C2%B7%20New%20B-segment%20battery-electric%20crossover%5DDeliverable_Based_WBS%201.pptx",
        "time": "16:09"
      },
      "9": {
        "name": "[RFP 15][VIKEN-2 · New B-segment battery-electric crossover]Risk_Buffer_Calculation_and_Assumptions_Log 1.pptx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP%2015%5D%5BVIKEN-2%20%C2%B7%20New%20B-segment%20battery-electric%20crossover%5DRisk_Buffer_Calculation_and_Assumptions_Log%201.pptx",
        "time": "16:09"
      }
    }
  },
  {
    "rfp": "RFP-16",
    "artifacts": {
      "0": {
        "name": "[RFP-16][Amir Hossain][Reign, No Rain] Infrastructure SecOps - v1.0.0.docx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-16%5D%5BAmir%20Hossain%5D%5BReign%2C%20No%20Rain%5D%20Infrastructure%20SecOps%20-%20v1.0.0.docx",
        "time": "12:33"
      },
      "3": {
        "name": "[RFP-16][Cloud-Infrastructure-&-Security-Operations]-RML-Status-v1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-16%5D%5BCloud-Infrastructure-%26-Security-Operations%5D-RML-Status-v1.0.0.xlsx",
        "time": "15:54"
      },
      "4": {
        "name": "[RFP-16][Cloud-Infrastructure-&-Security-Operations]-UCM-Classification-v1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-16%5D%5BCloud-Infrastructure-%26-Security-Operations%5D-UCM-Classification-v1.0.0.xlsx",
        "time": "15:54"
      },
      "5": {
        "name": "[RFP-16][Cloud-Infrastructure-&-Security-Operations]-RVW-Record-v1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-16%5D%5BCloud-Infrastructure-%26-Security-Operations%5D-RVW-Record-v1.0.0.xlsx",
        "time": "15:54"
      },
      "6": {
        "name": "[RFP-16][Cloud-Infrastructure-&-Security-Operations]-Risk-Assumption-Register-v1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-16%5D%5BCloud-Infrastructure-%26-Security-Operations%5D-Risk-Assumption-Register-v1.0.0.xlsx",
        "time": "15:54"
      },
      "8": {
        "name": "[RFP-16][Cloud-Infrastructure-&-Security-Operations]-Deliverable-WBS-v1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-16%5D%5BCloud-Infrastructure-%26-Security-Operations%5D-Deliverable-WBS-v1.0.0.xlsx",
        "time": "15:54"
      },
      "9": {
        "name": "[RFP-16][Cloud-Infrastructure-&-Security-Operations]-Risk-Buffer-Assumptions-v1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-16%5D%5BCloud-Infrastructure-%26-Security-Operations%5D-Risk-Buffer-Assumptions-v1.0.0.xlsx",
        "time": "15:54"
      },
      "10": {
        "name": "[RFP-16][Cloud-Infrastructure-&-Security-Operations]-Scope-Margin-Baseline-v1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-16%5D%5BCloud-Infrastructure-%26-Security-Operations%5D-Scope-Margin-Baseline-v1.0.0.xlsx",
        "time": "15:54"
      },
      "11": {
        "name": "[RFP-16][Cloud-Infrastructure-&-Security-Operations]-BRC-Decision-v1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-16%5D%5BCloud-Infrastructure-%26-Security-Operations%5D-BRC-Decision-v1.0.0.xlsx",
        "time": "15:54"
      },
      "12": {
        "name": "[RFP-16][Cloud-Infrastructure-&-Security-Operations]-Technical-Proposal-v1.0.0.pptx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-16%5D%5BCloud-Infrastructure-%26-Security-Operations%5D-Technical-Proposal-v1.0.0.pptx",
        "time": "16:24"
      }
    }
  },
  {
    "rfp": "RFP-17",
    "artifacts": {
      "0": {
        "name": "[RFP-17][Homayun Kabir][Full-Stack, Full Margin] ABC Corporation Warehouse Management Platform - v1.0.0.docx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-17%5D%5BHomayun%20Kabir%5D%5BFull-Stack%2C%20Full%20Margin%5D%20ABC%20Corporation%20Warehouse%20Management%20Platform%20-%20v1.0.0.docx",
        "time": "12:33"
      },
      "1": {
        "name": "[RFP-17][Full-Stack, Full Margin] Requirement Package V-1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-17%5D%5BFull-Stack%2C%20Full%20Margin%5D%20Requirement%20Package%20V-1.0.0.xlsx",
        "time": "15:29"
      },
      "2": {
        "name": "[RFP-17][Full-Stack, Full Margin] Open Questions Register V-1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-17%5D%5BFull-Stack%2C%20Full%20Margin%5D%20Open%20Questions%20Register%20V-1.0.0.xlsx",
        "time": "15:34"
      },
      "4": {
        "name": "[RFP-17][Full-Stack, Full Margin] UCM Classification V-1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-17%5D%5BFull-Stack%2C%20Full%20Margin%5D%20UCM%20Classification%20V-1.0.0.xlsx",
        "time": "15:38"
      },
      "5": {
        "name": "[RFP-17][Full-Stack, Full Margin] RVW Record V-1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-17%5D%5BFull-Stack%2C%20Full%20Margin%5D%20RVW%20Record%20V-1.0.0.xlsx",
        "time": "15:40"
      },
      "7": {
        "name": "[RFP-17][Full-Stack, Full Margin] Solution Approval V-1.0.0.pptx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-17%5D%5BFull-Stack%2C%20Full%20Margin%5D%20Solution%20Approval%20V-1.0.0.pptx",
        "time": "16:09"
      },
      "8": {
        "name": "[RFP-17][Full-Stack, Full Margin] Deliverable WBS V-1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-17%5D%5BFull-Stack%2C%20Full%20Margin%5D%20Deliverable%20WBS%20V-1.0.0.xlsx",
        "time": "15:46"
      },
      "9": {
        "name": "[RFP-17][Full-Stack, Full Margin] Risk Buffer + Assumptions V-1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-17%5D%5BFull-Stack%2C%20Full%20Margin%5D%20Risk%20Buffer%20%2B%20Assumptions%20V-1.0.0.xlsx",
        "time": "15:58"
      },
      "10": {
        "name": "[RFP-17][Full-Stack, Full Margin] Scope + Margin Baseline V-1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-17%5D%5BFull-Stack%2C%20Full%20Margin%5D%20Scope%20%2B%20Margin%20Baseline%20V-1.0.0.xlsx",
        "time": "15:54"
      }
    }
  },
  {
    "rfp": "RFP-18",
    "artifacts": {
      "0": {
        "name": "[RFP-18][Minhajur Rahman][Jack of All Stacks] JNGC - v1.0.0.docx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-18%5D%5BMinhajur%20Rahman%5D%5BJack%20of%20All%20Stacks%5D%20JNGC%20-%20v1.0.0.docx",
        "time": "12:33"
      },
      "2": {
        "name": "[RFP-18][Mall Core Renewal] Open Questions Register V-1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-18%5D%5BMall%20Core%20Renewal%5D%20Open%20Questions%20Register%20V-1.0.0.xlsx",
        "time": "15:54"
      },
      "4": {
        "name": "[RFP-18][Mall Core Renewal] UCM Version 1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-18%5D%5BMall%20Core%20Renewal%5D%20UCM%20Version%201.0.0.xlsx",
        "time": "15:54"
      },
      "5": {
        "name": "[RFP-18][Mall Core Renewal]  RVW Record V-1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-18%5D%5BMall%20Core%20Renewal%5D%20%20RVW%20Record%20V-1.0.0.xlsx",
        "time": "15:54"
      },
      "6": {
        "name": "[RFP-18][Mall Core Renewal] Risk-Assumption Register V-1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-18%5D%5BMall%20Core%20Renewal%5D%20Risk-Assumption%20Register%20V-1.0.0.xlsx",
        "time": "15:54"
      },
      "8": {
        "name": "[RFP-18][Mall Core Renewal] Deliverable WBSVersion 1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-18%5D%5BMall%20Core%20Renewal%5D%20Deliverable%20WBSVersion%201.0.0.xlsx",
        "time": "15:54"
      },
      "9": {
        "name": "[RFP-18][Mall Core Renewal]  Risk Buffer + Assumptions V-1.0.0 - Copy.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-18%5D%5BMall%20Core%20Renewal%5D%20%20Risk%20Buffer%20%2B%20Assumptions%20V-1.0.0%20-%20Copy.xlsx",
        "time": "15:54"
      },
      "10": {
        "name": "[RFP-18][Mall Core Renewal] Scope & Margin base line Version 1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-18%5D%5BMall%20Core%20Renewal%5D%20Scope%20%26%20Margin%20base%20line%20Version%201.0.0.xlsx",
        "time": "15:54"
      },
      "12": {
        "name": "[RFP-18][Mall Core Renewal] Technical Proposal Version 0.0.1.pptx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-18%5D%5BMall%20Core%20Renewal%5D%20Technical%20Proposal%20Version%200.0.1.pptx",
        "time": "16:36"
      }
    }
  },
  {
    "rfp": "RFP-19",
    "artifacts": {
      "0": {
        "name": "[RFP-19][Tareque Arefin][ERP-solutely Governed] TMart OneStock WMS - v1.0.0.docx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-19%5D%5BTareque%20Arefin%5D%5BERP-solutely%20Governed%5D%20TMart%20OneStock%20WMS%20-%20v1.0.0.docx",
        "time": "12:33"
      },
      "1": {
        "name": "[RFP-19] [TMart OneStock WMS] Requirement Package - v1.0.0.docx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-19%5D%20%5BTMart%20OneStock%20WMS%5D%20Requirement%20Package%20-%20v1.0.0.docx",
        "time": "15:38"
      },
      "2": {
        "name": "[RFP-19] [TMart OneStock WMS] Open Questions Register - v1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-19%5D%20%5BTMart%20OneStock%20WMS%5D%20Open%20Questions%20Register%20-%20v1.0.0.xlsx",
        "time": "15:38"
      },
      "3": {
        "name": "[RFP-19] [TMart OneStock WMS] RML status per requirement - v1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-19%5D%20%5BTMart%20OneStock%20WMS%5D%20RML%20status%20per%20requirement%20-%20v1.0.0.xlsx",
        "time": "15:38"
      },
      "4": {
        "name": "[RFP-19] [TMart OneStock WMS] UCM classification - v1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-19%5D%20%5BTMart%20OneStock%20WMS%5D%20UCM%20classification%20-%20v1.0.0.xlsx",
        "time": "15:38"
      },
      "5": {
        "name": "[RFP-19] [TMart OneStock WMS] Reverse Validation Workshop - v1.0.0.docx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-19%5D%20%5BTMart%20OneStock%20WMS%5D%20Reverse%20Validation%20Workshop%20-%20v1.0.0.docx",
        "time": "15:38"
      },
      "6": {
        "name": "[RFP-19] [TMart OneStock WMS] Risk Assumption Register - v1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-19%5D%20%5BTMart%20OneStock%20WMS%5D%20Risk%20Assumption%20Register%20-%20v1.0.0.xlsx",
        "time": "15:38"
      },
      "7": {
        "name": "[RFP-19] [TMart OneStock WMS] Solution Approval note - v1.0.0.docx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-19%5D%20%5BTMart%20OneStock%20WMS%5D%20Solution%20Approval%20note%20-%20v1.0.0.docx",
        "time": "15:38"
      },
      "8": {
        "name": "[RFP-19] [TMart OneStock WMS] Deliverable-based WBS - v1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-19%5D%20%5BTMart%20OneStock%20WMS%5D%20Deliverable-based%20WBS%20-%20v1.0.0.xlsx",
        "time": "15:44"
      },
      "9": {
        "name": "[RFP-19] [TMart OneStock WMS] Risk Buffer + Assumptions - v1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-19%5D%20%5BTMart%20OneStock%20WMS%5D%20Risk%20Buffer%20%2B%20Assumptions%20-%20v1.0.0.xlsx",
        "time": "16:40"
      },
      "10": {
        "name": "[RFP-19] [TMart OneStock WMS] Scope + Margin Baseline - v1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-19%5D%20%5BTMart%20OneStock%20WMS%5D%20Scope%20%2B%20Margin%20Baseline%20-%20v1.0.0.xlsx",
        "time": "16:54"
      },
      "11": {
        "name": "[RFP-19] [TMart OneStock WMS] BRC Decision - v1.0.0.docx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-19%5D%20%5BTMart%20OneStock%20WMS%5D%20BRC%20Decision%20-%20v1.0.0.docx",
        "time": "16:54"
      },
      "12": {
        "name": "[RFP-19] [TMart OneStock WMS] Technical Proposal - v1.0.0.pptx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-19%5D%20%5BTMart%20OneStock%20WMS%5D%20Technical%20Proposal%20-%20v1.0.0.pptx",
        "time": "16:54"
      }
    }
  },
  {
    "rfp": "RFP-20",
    "artifacts": {
      "0": {
        "name": "[RFP-20][Susanta Kumar Saha][Query Everything] TC Data Migration - v1.0.0.docx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-20%5D%5BSusanta%20Kumar%20Saha%5D%5BQuery%20Everything%5D%20TC%20Data%20Migration%20-%20v1.0.0.docx",
        "time": "12:33"
      },
      "1": {
        "name": "[RFP-20] [Enterprise Engineering Data Migration to Siemens Teamcenter] Requirement Package V-1.0.0.pptx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-20%5D%20%5BEnterprise%20Engineering%20Data%20Migration%20to%20Siemens%20Teamcenter%5D%20Requirement%20Package%20V-1.0.0.pptx",
        "time": "16:05"
      },
      "2": {
        "name": "[RFP-20] [Enterprise Engineering Data Migration to Siemens Teamcenter] Open Questions Register V-1.0.0.pptx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-20%5D%20%5BEnterprise%20Engineering%20Data%20Migration%20to%20Siemens%20Teamcenter%5D%20Open%20Questions%20Register%20V-1.0.0.pptx",
        "time": "16:05"
      },
      "4": {
        "name": "[RFP-20] [Enterprise Engineering Data Migration to Siemens Teamcenter] UCM Classification V-1.0.0.pptx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-20%5D%20%5BEnterprise%20Engineering%20Data%20Migration%20to%20Siemens%20Teamcenter%5D%20UCM%20Classification%20V-1.0.0.pptx",
        "time": "16:05"
      },
      "5": {
        "name": "[RFP-20] [Enterprise Engineering Data Migration to Siemens Teamcenter] RVW Record V-1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-20%5D%20%5BEnterprise%20Engineering%20Data%20Migration%20to%20Siemens%20Teamcenter%5D%20RVW%20Record%20V-1.0.0.xlsx",
        "time": "16:05"
      },
      "7": {
        "name": "[RFP-20] [Enterprise Engineering Data Migration to Siemens Teamcenter] Solution Approval V-1.0.0.pptx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-20%5D%20%5BEnterprise%20Engineering%20Data%20Migration%20to%20Siemens%20Teamcenter%5D%20Solution%20Approval%20V-1.0.0.pptx",
        "time": "16:05"
      },
      "8": {
        "name": "[RFP-20] [Enterprise Engineering Data Migration to Siemens Teamcenter] WBS V-1.0.1.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-20%5D%20%5BEnterprise%20Engineering%20Data%20Migration%20to%20Siemens%20Teamcenter%5D%20WBS%20V-1.0.1.xlsx",
        "time": "16:51"
      },
      "9": {
        "name": "[RFP-20] [Enterprise Engineering Data Migration to Siemens Teamcenter] Risk_Buffer_Calculation V-1.0.0.pptx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-20%5D%20%5BEnterprise%20Engineering%20Data%20Migration%20to%20Siemens%20Teamcenter%5D%20Risk_Buffer_Calculation%20V-1.0.0.pptx",
        "time": "16:05"
      },
      "10": {
        "name": "[RFP-20] [Enterprise Engineering Data Migration to Siemens Teamcenter] Margin_Baseline V-1.0.1.pptx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-20%5D%20%5BEnterprise%20Engineering%20Data%20Migration%20to%20Siemens%20Teamcenter%5D%20Margin_Baseline%20V-1.0.1.pptx",
        "time": "16:51"
      },
      "11": {
        "name": "[RFP-20] [Enterprise Engineering Data Migration to Siemens Teamcenter] BRC Decision V1.0.0.pptx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-20%5D%20%5BEnterprise%20Engineering%20Data%20Migration%20to%20Siemens%20Teamcenter%5D%20BRC%20Decision%20V1.0.0.pptx",
        "time": "16:05"
      },
      "12": {
        "name": "[RFP-20] [Enterprise Engineering Data Migration to Siemens Teamcenter] Technical Proposal V-1.0.1.pptx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-20%5D%20%5BEnterprise%20Engineering%20Data%20Migration%20to%20Siemens%20Teamcenter%5D%20Technical%20Proposal%20V-1.0.1.pptx",
        "time": "16:51"
      }
    }
  }
];
