/* GENERATED by tools/build_upload_index.py — do not edit by hand. */

const UPLOAD_INDEX_BUILT = "1 Aug 2026 · 15:18";
const UPLOAD_INDEX = [
  {
    "rfp": "RFP-01",
    "artifacts": {
      "0": {
        "name": "[RFP-01][Sajidul Huq][The Scope Creepers] Mizuho SalaryDirect - v1.0.0.docx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-01%5D%5BSajidul%20Huq%5D%5BThe%20Scope%20Creepers%5D%20Mizuho%20SalaryDirect%20-%20v1.0.0.docx",
        "time": "12:33"
      }
    }
  },
  {
    "rfp": "RFP-02",
    "artifacts": {
      "0": {
        "name": "[RFP-02][Shahjalal Hossain][404 - Free Work Not Found] BidHub Auction Marketplace - v1.0.0.docx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-02%5D%5BShahjalal%20Hossain%5D%5B404%20-%20Free%20Work%20Not%20Found%5D%20BidHub%20Auction%20Marketplace%20-%20v1.0.0.docx",
        "time": "12:33"
      },
      "1": {
        "name": "[RFP-02][BidHub Auction Marketplace] Requirement Package - v1.0.0.zip",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-02%5D%5BBidHub%20Auction%20Marketplace%5D%20Requirement%20Package%20-%20v1.0.0.zip",
        "time": "15:06"
      },
      "4": {
        "name": "[RFP-02][BidHub Auction Marketplace] UCM Classification -v1.0.0.xlsx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-02%5D%5BBidHub%20Auction%20Marketplace%5D%20UCM%20Classification%20-v1.0.0.xlsx",
        "time": "15:16"
      }
    }
  },
  {
    "rfp": "RFP-03",
    "artifacts": {
      "0": {
        "name": "[RFP-03][Abdul Halim][Ctrl+Alt+Deliver] Midori-Home - v1.0.0.docx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-03%5D%5BAbdul%20Halim%5D%5BCtrl%2BAlt%2BDeliver%5D%20Midori-Home%20-%20v1.0.0.docx",
        "time": "12:33"
      }
    }
  },
  {
    "rfp": "RFP-04",
    "artifacts": {
      "0": {
        "name": "[RFP-04][Dewan Shamsul Alam][Swipe Right to Sign Off] NovaCart Mobile - v1.0.0.docx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-04%5D%5BDewan%20Shamsul%20Alam%5D%5BSwipe%20Right%20to%20Sign%20Off%5D%20NovaCart%20Mobile%20-%20v1.0.0.docx",
        "time": "12:33"
      }
    }
  },
  {
    "rfp": "RFP-05",
    "artifacts": {
      "0": {
        "name": "[RFP-05][Mostafizur Rahman][Push Notification Nation] Astra Mobile Pack - V1.0.0.docx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-05%5D%5BMostafizur%20Rahman%5D%5BPush%20Notification%20Nation%5D%20Astra%20Mobile%20Pack%20-%20V1.0.0.docx",
        "time": "15:00"
      }
    }
  },
  {
    "rfp": "RFP-06",
    "artifacts": {
      "0": {
        "name": "[RFP-06][Mamun Ahmed Khan][The App-solute Owners] SolaraLife - v1.0.0.docx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-06%5D%5BMamun%20Ahmed%20Khan%5D%5BThe%20App-solute%20Owners%5D%20SolaraLife%20-%20v1.0.0.docx",
        "time": "12:33"
      }
    }
  },
  {
    "rfp": "RFP-07",
    "artifacts": {
      "0": {
        "name": "[RFP-07][Dipankar Das Shovon][Bare Metal Bidders] Kitagawa Battery - v1.0.0.docx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-07%5D%5BDipankar%20Das%20Shovon%5D%5BBare%20Metal%20Bidders%5D%20Kitagawa%20Battery%20-%20v1.0.0.docx",
        "time": "12:33"
      }
    }
  },
  {
    "rfp": "RFP-08",
    "artifacts": {
      "0": {
        "name": "[RFP-08][Iftekhar Uddin Ahmed][The Ctrl Freaks] Hoshino Sight 8 - v1.0.0.docx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-08%5D%5BIftekhar%20Uddin%20Ahmed%5D%5BThe%20Ctrl%20Freaks%5D%20Hoshino%20Sight%208%20-%20v1.0.0.docx",
        "time": "12:33"
      }
    }
  },
  {
    "rfp": "RFP-09",
    "artifacts": {
      "0": {
        "name": "[RFP-09][Shaiful Islam][React & Sign-Off] FlyerBank Direct AMS - v1.0.0.docx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-09%5D%5BShaiful%20Islam%5D%5BReact%20%26%20Sign-Off%5D%20FlyerBank%20Direct%20AMS%20-%20v1.0.0.docx",
        "time": "12:33"
      }
    }
  },
  {
    "rfp": "RFP-10",
    "artifacts": {
      "0": {
        "name": "[RFP-10][Partha Pratim Sarkar][The Baseline Defenders] Wakaba - v1.0.0.docx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-10%5D%5BPartha%20Pratim%20Sarkar%5D%5BThe%20Baseline%20Defenders%5D%20Wakaba%20-%20v1.0.0.docx",
        "time": "12:33"
      }
    }
  },
  {
    "rfp": "RFP-11",
    "artifacts": {
      "0": {
        "name": "[RFP-11][ABM Mahbubur Rahman][Sixty-Seven Shades of Ownership] Legacy-Migration Suzuran SPL StockOne - v1.0.0.docx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-11%5D%5BABM%20Mahbubur%20Rahman%5D%5BSixty-Seven%20Shades%20of%20Ownership%5D%20Legacy-Migration%20Suzuran%20SPL%20StockOne%20-%20v1.0.0.docx",
        "time": "12:33"
      }
    }
  },
  {
    "rfp": "RFP-12",
    "artifacts": {
      "0": {
        "name": "[RFP-12][Himadri Mondol][Not My Bug Anymore] Nexus-Telecom QA-PartneR - v1.0.0.docx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-12%5D%5BHimadri%20Mondol%5D%5BNot%20My%20Bug%20Anymore%5D%20Nexus-Telecom%20QA-PartneR%20-%20v1.0.0.docx",
        "time": "12:33"
      }
    }
  },
  {
    "rfp": "RFP-13",
    "artifacts": {
      "0": {
        "name": "[RFP-13][Nadim Hossain][Test Case Closed] Migration-QA - v1.0.0.pdf",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-13%5D%5BNadim%20Hossain%5D%5BTest%20Case%20Closed%5D%20Migration-QA%20-%20v1.0.0.pdf",
        "time": "12:33"
      }
    }
  },
  {
    "rfp": "RFP-14",
    "artifacts": {
      "0": {
        "name": "[RFP-14][Azizul Islam][The Tolerance Negotiators] NORDTEK OY NT-2026-KOSKI2-BD - v1.0.0.docx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-14%5D%5BAzizul%20Islam%5D%5BThe%20Tolerance%20Negotiators%5D%20NORDTEK%20OY%20NT-2026-KOSKI2-BD%20-%20v1.0.0.docx",
        "time": "12:33"
      }
    }
  },
  {
    "rfp": "RFP-15",
    "artifacts": {
      "0": {
        "name": "[RFP-15][Sayeedul Islam][Torque of the Town] Nordkaross VIKEN - v1.0.0.pdf",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-15%5D%5BSayeedul%20Islam%5D%5BTorque%20of%20the%20Town%5D%20Nordkaross%20VIKEN%20-%20v1.0.0.pdf",
        "time": "12:33"
      }
    }
  },
  {
    "rfp": "RFP-16",
    "artifacts": {
      "0": {
        "name": "[RFP-16][Amir Hossain][Reign, No Rain] Infrastructure SecOps - v1.0.0.docx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-16%5D%5BAmir%20Hossain%5D%5BReign%2C%20No%20Rain%5D%20Infrastructure%20SecOps%20-%20v1.0.0.docx",
        "time": "12:33"
      }
    }
  },
  {
    "rfp": "RFP-17",
    "artifacts": {
      "0": {
        "name": "[RFP-17][Homayun Kabir][Full-Stack, Full Margin] ABC Corporation Warehouse Management Platform - v1.0.0.docx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-17%5D%5BHomayun%20Kabir%5D%5BFull-Stack%2C%20Full%20Margin%5D%20ABC%20Corporation%20Warehouse%20Management%20Platform%20-%20v1.0.0.docx",
        "time": "12:33"
      }
    }
  },
  {
    "rfp": "RFP-18",
    "artifacts": {
      "0": {
        "name": "[RFP-18][Minhajur Rahman][Jack of All Stacks] JNGC - v1.0.0.docx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-18%5D%5BMinhajur%20Rahman%5D%5BJack%20of%20All%20Stacks%5D%20JNGC%20-%20v1.0.0.docx",
        "time": "12:33"
      }
    }
  },
  {
    "rfp": "RFP-19",
    "artifacts": {
      "0": {
        "name": "[RFP-19][Tareque Arefin][ERP-solutely Governed] TMart OneStock WMS - v1.0.0.docx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-19%5D%5BTareque%20Arefin%5D%5BERP-solutely%20Governed%5D%20TMart%20OneStock%20WMS%20-%20v1.0.0.docx",
        "time": "12:33"
      }
    }
  },
  {
    "rfp": "RFP-20",
    "artifacts": {
      "0": {
        "name": "[RFP-20][Susanta Kumar Saha][Query Everything] TC Data Migration - v1.0.0.docx",
        "url": "https://nextcloud.bjitgroup.com/index.php/s/qSywfyXqQgxreRj/download?path=%2F&files=%5BRFP-20%5D%5BSusanta%20Kumar%20Saha%5D%5BQuery%20Everything%5D%20TC%20Data%20Migration%20-%20v1.0.0.docx",
        "time": "12:33"
      }
    }
  }
];
