#!/usr/bin/env python3
"""Regenerate the Upload Artifacts submission index from a local folder.

Usage:
    python3 tools/build_upload_index.py <uploads-folder>

Point <uploads-folder> at the locally synced copy of the shared upload
folder (OneDrive sync / manual download). The script:

  1. parses each file name against the convention
         [RFP XX][Customer Name][Team Name] Project Name V-x.y.z.ext
     (the RFP tag is what actually matters — customer/team are looked up)
  2. classifies every file into one of the 12 mandatory artifacts by
     keywords in the name,
  3. keeps only the latest copy per team+artifact (highest V-x.y.z,
     ties broken by file modification time),
  4. copies the winners into assets/uploads/ with URL-safe names, and
  5. rewrites js/uploads-index.js.

Then commit + push to publish the refreshed index.
"""

import os, re, shutil, sys, json
from datetime import datetime

SITE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEST = os.path.join(SITE, "assets", "uploads")
OUT = os.path.join(SITE, "js", "uploads-index.js")

# keyword rules checked IN ORDER — first match wins (specific before generic)
RULES = [
    (9,  ["risk buffer", "estimation assumption", "assumptions log", "buffer"]),
    (1,  ["requirement package", "requirements package", "req package", "requirement pack"]),
    (2,  ["open question", "questions register", "oqr"]),
    (3,  ["rml"]),
    (4,  ["ucm"]),
    (5,  ["rvw", "reverse validation"]),
    (7,  ["solution approval", "solution validation", "technology risk", "solution note"]),
    (8,  ["wbs", "work breakdown"]),
    (10, ["scope baseline", "margin baseline", "baseline", "margin"]),
    (11, ["brc", "go-no-go", "go no go", "go/no-go", "bid review"]),
    (6,  ["risk", "assumption"]),
    (9,  ["estimation", "estimate"]),
    (12, ["proposal", "presentation", "pitch", "deck"]),
]

VER = re.compile(r"v[\s\-_]?(\d+)[._](\d+)[._](\d+)", re.I)
RFP = re.compile(r"\[?\s*RFP[\s\-_]?(\d{1,2})\s*\]?", re.I)


def classify(name):
    low = name.lower()
    for art, keys in RULES:
        if any(k in low for k in keys):
            return art
    return None


def version_of(name):
    m = VER.search(name)
    return tuple(int(g) for g in m.groups()) if m else (0, 0, 0)


def main():
    if len(sys.argv) != 2 or not os.path.isdir(sys.argv[1]):
        sys.exit(__doc__)
    src = sys.argv[1]

    best = {}   # (rfp, artifact) -> (version, mtime, path, fname)
    skipped = []
    for f in sorted(os.listdir(src)):
        p = os.path.join(src, f)
        if not os.path.isfile(p) or f.startswith((".", "~$")):
            continue
        m = RFP.search(f)
        if not m:
            skipped.append(f + "  (no RFP tag)")
            continue
        rfp = f"RFP-{int(m.group(1)):02d}"
        art = classify(f)
        if art is None:
            skipped.append(f + "  (artifact type not recognized)")
            continue
        key = (rfp, art)
        cand = (version_of(f), os.path.getmtime(p), p, f)
        if key not in best or cand[:2] > best[key][:2]:
            best[key] = cand

    if os.path.isdir(DEST):
        shutil.rmtree(DEST)
    os.makedirs(DEST)

    index = {}
    for (rfp, art), (_ver, mtime, p, f) in sorted(best.items()):
        safe = re.sub(r"[^A-Za-z0-9.-]+", "_", f).strip("_")
        shutil.copy2(p, os.path.join(DEST, safe))
        t = datetime.fromtimestamp(mtime).strftime("%H:%M")
        index.setdefault(rfp, {})[str(art)] = {
            "name": f, "url": "assets/uploads/" + safe, "time": t}

    entries = [{"rfp": r, "artifacts": a} for r, a in sorted(index.items())]
    body = json.dumps(entries, indent=2, ensure_ascii=False)
    with open(OUT, "w", encoding="utf-8") as fp:
        fp.write("/* GENERATED by tools/build_upload_index.py — do not edit by hand.\n"
                 f"   Last build: {datetime.now().strftime('%Y-%m-%d %H:%M')} */\n\n"
                 f"const UPLOAD_INDEX = {body};\n")

    print(f"{sum(len(a) for a in index.values())} files indexed "
          f"across {len(index)} teams -> {os.path.relpath(OUT, SITE)}")
    if skipped:
        print("\nSkipped (fix the file name and rerun):")
        for s in skipped:
            print("  -", s)


if __name__ == "__main__":
    main()
